name: Android CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'
  pull_request:
  workflow_dispatch:
   inputs:
     VERSION:
      description: 'VERSION'

jobs:
  build_CI:
    name: Build Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main

      - name: Grant Permissions for Gradle
        run: chmod +x gradlew

      - name: Build Release APK
        id: build
        run: ./gradlew assembleRelease --parallel
      
      - name: Upload artifact
        uses: actions/upload-artifact@main
        if: ${{ !github.head_ref }}
        with:
          name: sora-editor.apk
          path: app/build/outputs/apk/release/*.apk
  create_release:
    needs: build_CI
    runs-on: ubuntu-latest
    steps:
     - name: download artifact
       uses: actions/download-artifact@main
       with:
          path: release
          merge-multiple: true
     - name: display release-assets
       run: tree ${{ github.workspace }}/release
     - name: Upload release build
       uses: softprops/action-gh-release@master
       with:
        tag_name: "${{ github.event.inputs.VERSION }}"
        fail_on_unmatched_files: true
        files: release/*
